#!/usr/bin/env python3
# BSD 3-Clause License
#
# Copyright (c) 2026, NTNU Autonomous Robots Lab
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
"""Load a previously generated EQA test split."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

from simulation_manager_ros.data import DataConfig, load_eqa_data

DATASET_ALIASES = {
    "openeqa": "openeqa",
    "exploreeqa": "exploreeqa",
}


def _load_base_data_config(config_path: Path) -> DataConfig:
    with config_path.open(encoding="utf-8") as file:
        raw_config = yaml.safe_load(file) or {}
    config_data = raw_config.get("data", raw_config)
    return DataConfig(**config_data)


def load_test_split(
    config_path: Path, split_manifest_path: Path, dataset: str
) -> list[dict[str, Any]]:
    base_config = _load_base_data_config(config_path)
    dataset_config = DataConfig(
        **{
            **base_config.__dict__,
            "dataset": DATASET_ALIASES[dataset],
            "load_test_split_only": True,
            "test_split_manifest_path": str(split_manifest_path),
        }
    )
    return load_eqa_data(dataset_config, filter_floorplan=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Load a previously generated OpenEQA or ExploreEQA test split."
    )
    parser.add_argument(
        "--config",
        type=Path,
        required=True,
        help="Path to a YAML config that can be parsed as DataConfig.",
    )
    parser.add_argument(
        "--split-manifest",
        type=Path,
        required=True,
        help="Path to the JSON split manifest generated by create_eqa_test_splits.py.",
    )
    parser.add_argument(
        "--dataset",
        choices=sorted(DATASET_ALIASES.keys()),
        required=True,
        help="Dataset split to load.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional path to write the loaded normalized episodes as JSON.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    episodes = load_test_split(args.config, args.split_manifest, args.dataset)
    print(f"Loaded {len(episodes)} test episodes for {args.dataset}.")

    if episodes:
        print(f"First question_id: {episodes[0]['question_id']}")

    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open("w", encoding="utf-8") as file:
            json.dump(episodes, file, indent=2)
            file.write("\n")
        print(f"Saved normalized test episodes to {args.output}")


if __name__ == "__main__":
    main()
